### PR TITLE
Phase7.1: Fixup the commits

### PR DESCRIPTION
**Pull request by sk-ip**
- Add the scorer for XGBClassifier model
- Fixup the commits

Addresses #732

Signed-off-by: Sudhanshu Sudhanshukumar5459@gmail.com

### CODE REVIEW

**Comment by pdxjohnny** [comment]
Sorry this has taken so long, it all looks great! Let's just reword some of the commit messages so that we don't have duplicates, and `fixup` or `squash` where appropriate to merge commits to the same files for the same reasons into a single commit.

For example I start by looking at the `--oneline` view

```console
$ git log --oneline
9b179560d model: scratch: fix the example tests
7b0d2ad0d model: scratch: fix the example tests
```

Then I look at the `--stat` view so I can see the files changed

```console
$ git log --stat
commit 9b179560dd9258ac12539e092b7d5f0b35af3942
Author: Sudhanshu kumar <sudhanshukumar5459@gmail.com>
Date:   Tue Sep 8 18:03:25 2020 +0000

    model: scratch: fix the example tests

 model/scratch/examples/scratchlgrsag/test_scratchlgrsag.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

commit 7b0d2ad0def366bb2fba63daebc78b802d6f6497
Author: Sudhanshu kumar <sudhanshukumar5459@gmail.com>
Date:   Tue Sep 8 17:58:38 2020 +0000

    model: scratch: fix the example tests

 model/scratch/examples/scratchlgrsag/test_scratchlgrsag.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

Finally I look at the changes to the files to make sure it makes sense to combine the commits

```diff
```

In this case it makes sense for us to merge those two commits into a single commit (which I have done and I force pushed)

> When pulling down a branch that has been forced pushed
> to by someone else or another machine, I find it's easiest to do a
> `git reset --hard HEAD~NUMBER_OF_COMMITS_IN_THE_PR_OR_JUST_SOME_LARGE_NUMBER_YOU_KNOW_IS_GOING_TO_BE_GREATER_THAN_THAT_NUMBER_SO_YOU_DO_NOT_HAVE_TO_COUNT_OR_LOOK`
> Then I do a `git pull` (obviously being on the branch in question)

---

In the case of `model/transformers` we've removed that from the master branch and moved it to https://github.com/dffml/dffml-model-transformers due to needing to update it and it not working at the moment.

So you can rebase and `drop` any commits where we touch files there. We'll need them later though so following this: https://stackoverflow.com/questions/920165/how-to-extract-a-git-subdirectory-and-make-a-submodule-out-of-it

I split out the commits you made to `model/transformers`

```console
$ git subtree split --prefix=model/transformers --branch=dffml-model-transformers-accuracy-staging
```

And put them on a separate branch here: https://github.com/dffml/dffml-model-transformers/commits/dffml-model-transformers-accuracy-staging. This way we can safely remove those commits without loosing the work you've done since we'll need those commits when we fix the rest of `model/transformers`.

The following commits can be removed (which I did since I'm here doing it anyway).

```
0d2fe04 model: transformers: examples: ner: Use the tner scorer
2770a48 model: transformers: qa: Add the tqa scorer in examples
1c3812c model: transformers: accuracy: Add necessary imports to qa accuracy
28c9de6 model: transformers: accuracy: classification: Add the necessary imports
095ccf8 model: transformers: accuracy: Use mctx instead of self
65f4ba2 model: transformers: accuracy: Add the init file
255e2bc model: transformers: accuracy: Add the qa scorer
7af8157 model: transformers: accuracy: Add the ner scorer
50eae93 model: transformers: accuracy: Add the classification scorer
dd12eec model: transformers: qa: Add the correct scorer
20aaeeb model: transformers: qa: Add the tqa scorer
7635af7 model: transformers: ner: Add the correct scorer
7fff2e3 model: transformers: ner: Add the tner scorer
e80a918 model: transformers: classification: Add the correct scorer
0a57966 model: transformers: classification: Add the tclf scorer
939d84e model: transformers: setup: Add the scorers
ac51cdf model: transformers: classification: Change the scorer
03f318d model: transformers: classification: add the method to modelcontext
584fc08 model: transformers: qa: Remove the accuracy method
3b30d03 model: transformers: ner: Remove the accuracy method
3d15e72 model: transformers: classification: Remove the accuracy method
215e196 model: transformers: tests: Use the high level accuracy
481e118 model: transformers: tests: Add the scorer to the tests
6eaf38d model: transformers: tests: Add the scorer to the tests
2631174 model: transformers: tests: Add the scorer to the tests
fac58b6 model: transformers: tests: Add the scorer to the tests
1964c97 model: transformers: tests: Add the scorer to the tests
d3812e4 model: transformers: tests: Add the scorer to the tests
222eb91 model: transformers: qa: examples: Add the scorer to cli
7040893 model: transformers: ner: examples: Add the scorer to python example
3d319a3 model: transformers: ner: examples: Add the scorer
11486a1 model: transformers: classification: examples: Add the scorer
1dad850 model: transformers: qa: Update the accuracy method to take accuracy parameter
7b3fab1 model: transformers: ner: Update the accuracy method to take accuracy parameter
5469473 model: transformers: classification: Update the accuracy method to take accuracy parameter
```

---

Last thing: Can you make sure that we capitalized all commit messages appropriately?

`model: scratch: fix the example tests` was the only one I saw offhand but if there are more please check that out

**Comment by pdxjohnny** [comment]
Thanks again! This is great work!

**Comment by sk-ip** [comment]
@pdxjohnny 
So i went over the suggestions you gave and have made the changes accordingly, I would like to give a disclaimer that while rebasing the commits I made some few mistakes, such as i accidently fixup two different files under same commit, so i redid that, by breaking the commit into multiple commits. 
Also there were some commits which i try to fixup but it started giving conflicts, so i made some new commits and fixup the commits for the same file. to fix the conflicting issues.

**Comment by pdxjohnny** [comment]
@sk-ip You did great work! There are still just a few of the commits that need to be more descriptive / are duplicate messages / there is one `Rename ...` that doesn't follow the format. Content looks great, if you can double check and fix those I'll merge. Let me know if you need any advice on anything.

**Comment by pdxjohnny** [comment]
We just want to be sure to get these 100% correct since they'll all be in master branch one day!

**Pull request merged**
