### PR TITLE
model: Consolidated self.location as a property of baseclass

### PR DESCRIPTION
**Pull request by programmer290399**
* Fixes:#1260
* Ready for review, ping @pdxjohnny

### CODE REVIEW

**Comment by programmer290399** [comment]
* `Tests / lint (changelog, 3.7, 12.x)` is failing because I haven't added anything in it as this is a refactor and not something that should go on changelog.

**Comment by pdxjohnny** [comment]
Is this still WIP?

**Comment by programmer290399** [comment]
> Is this still WIP?

Yes, actually It was messed up by mistake when I re-based it with master last time and now I have rolled it back to the initial commit on this PR, have to make a few more replacements and then it would be good to go. I will try to get it merged in next weekly meet.

**Comment by programmer290399** [comment]
* All failing errors are also failing on master, other than commit lint, which is failing due to typo in spelling of changelog.

**Review by pdxjohnny — APPROVED** [review]

**Pull request merged**
