### PR TITLE
Removed --use-feature=2020-resolver issue #912

### PR DESCRIPTION
**Pull request by Devansh252**
Removed --use-feature=2020-resolver

### CODE REVIEW

**Comment by pdxjohnny** [comment]
Hi @Devansh252, I'd recommend creating one pull request with all the required changes. You can make multiple commits on a branch, and push to GitHub after each commit. Please be sure to let us know when your pull request is ready for review. Thanks! Let me know if you have any questions.

**Comment by Devansh252** [comment]
> Hi @Devansh252, I'd recommend creating one pull request with all the required changes. You can make multiple commits on a branch, and push to GitHub after each commit. Please be sure to let us know when your pull request is ready for review. Thanks! Let me know if you have any questions.

what changes will be required in code like those in .rst files. 
like in this section present in dffml/docs/tutorials/sources/complex.rst
image

**Comment by pdxjohnny** [comment]
That's a good example of where we want to remove the `--use-feature=2020-resolver` from the command in the example. Most of these removals will be in examples I think.

**Comment by pdxjohnny** [comment]
I just pushed f3f3592e85bbfb4c9d128f73ad8064c14b6d983d. That change I just pushed removed a check we had within the tests to make sure that every `pip install` command had the `--use-feature=2020-resolver` argument.

I'd recommend doing the following commands. This shows what it looks like when I do it, so the pdxjohnny `remote` is the URL to my fork of DFFML:

```console
$ git remote -v
origin  git@github.com:intel/dffml (fetch)
origin  git@github.com:intel/dffml (push)
pdxjohnny       git@github.com:pdxjohnny/dffml (fetch)
pdxjohnny       git@github.com:pdxjohnny/dffml (push)
$ git fetch --all
Fetching origin
remote: Enumerating objects: 432, done.
remote: Counting objects: 100% (432/432), done.
remote: Compressing objects: 100% (89/89), done.
remote: Total 273 (delta 208), reused 246 (delta 181), pack-reused 0
Receiving objects: 100% (273/273), 2.70 MiB | 21.64 MiB/s, done.
Resolving deltas: 100% (208/208), completed with 142 local objects.
From github.com:intel/dffml
   5672cb22..a460449c  gh-pages   -> origin/gh-pages
Fetching pdxjohnny
$ git rebase origin/master
Current branch master is up to date.
```

The second command pulls down recent changes, the final command tells git to take the most recent changes to the `master` branch and make sure whatever branch you're working on has those changes. This should add the commit I talked about just added to your branch, which will make it so that if you removed all the correct things the tests will pass in this Pull Request.

**Comment by Devansh252** [comment]
> I just pushed [f3f3592](https://github.com/intel/dffml/commit/f3f3592e85bbfb4c9d128f73ad8064c14b6d983d). That change I just pushed removed a check we had within the tests to make sure that every `pip install` command had the `--use-feature=2020-resolver` argument.
> 
> I'd recommend doing the following commands. This shows what it looks like when I do it, so the pdxjohnny `remote` is the URL to my fork of DFFML:
> 
> ```
> $ git remote -v
> origin  git@github.com:intel/dffml (fetch)
> origin  git@github.com:intel/dffml (push)
> pdxjohnny       git@github.com:pdxjohnny/dffml (fetch)
> pdxjohnny       git@github.com:pdxjohnny/dffml (push)
> $ git fetch --all
> Fetching origin
> remote: Enumerating objects: 432, done.
> remote: Counting objects: 100% (432/432), done.
> remote: Compressing objects: 100% (89/89), done.
> remote: Total 273 (delta 208), reused 246 (delta 181), pack-reused 0
> Receiving objects: 100% (273/273), 2.70 MiB | 21.64 MiB/s, done.
> Resolving deltas: 100% (208/208), completed with 142 local objects.
> From github.com:intel/dffml
>    5672cb22..a460449c  gh-pages   -> origin/gh-pages
> Fetching pdxjohnny
> $ git rebase origin/master
> Current branch master is up to date.
> ```
> 
> The second command pulls down recent changes, the final command tells git to take the most recent changes to the `master` branch and make sure whatever branch you're working on has those changes. This should add the commit I talked about just added to your branch, which will make it so that if you removed all the correct things the tests will pass in this Pull Request.

I updated my forked repo , with the necessary changes , but still some tests are failing , are these changes are incorrect ? what I have comited till now?

**Pull request closed without merging**
