### PR TITLE
added sphinx copy button

### LINKED ISSUE #1016: docs: Add Sphinx-copybutton
Add support of  [Sphinx-copybutthon](https://sphinx-copybutton.readthedocs.io/en/latest/). Which adds a little “copy” button to the right of the code blocks.

### PR DESCRIPTION
**Pull request by rajpratyush**
added code for  implementing sphinx copy button

 Closes #1016 
 
 @pdxjohnny can you please review this Pull Request

### CODE REVIEW

**Comment by aryanxk02** [comment]
@rajpratyush  hey, what exactly went wrong?

**Comment by rajpratyush** [comment]
@aryanxk02 I dont think anything went wrong as such

**Comment by pdxjohnny** [comment]
I believe you need to rebase in the master branch with the fix for the new version of copybutton.js

**Comment by pdxjohnny** [comment]
This replaces the `copybutton.js` that we already have... If you want to continue with this, please make sure that both are supported.

**Comment by rajpratyush** [comment]
Yes it is supported i have tried

**Comment by pdxjohnny** [comment]
It looks like the docs build is failing. Also, it looks like you're using the deprecated APIs for adding stylesheets and js. Do you have a reason for changing those lines? I don't see anything about that in the sphinx-copybutton docs?

**Comment by rajpratyush** [comment]
Lemme change it again and push a commit by today

**Comment by rajpratyush** [comment]
@pdxjohnny can you provide me the updated api's i could not find thm

**Pull request closed without merging**
